### ISSUE TITLE
Cannot create student

### ISSUE THREAD

**Issue by mhraihan** [yungifez/skuul#137]
Hi,
when trying to create the student, got the error
Undefined array key 0

```
    public function offsetGet($key): mixed

    {

        return $this->items[$key];

    }
```

do you've any idea, how can I solve the issue?

thanks

**Comment by yungifez** [comment]
Do you have a screenshot and a stack trace

**Comment by yungifez** [comment]
No worries

Ive narrowed down the issue 

For the mean time, you can bypass this error by creating a class and a section in that class

Ill issue a fix as soon as possible to properly handle this issue

**Comment by yungifez** [comment]
For a more detailed explanation of this issue

In the createstudent livewire class i have this 

` php       $this->sections = collect(App::make(MyClassService::class)->getClassById($this->myClasses[0]['id'])->sections);`

Which fails if classes are not present in the system

**Comment by yungifez** [comment]
Thank you for ysing and checking out skuul 

Expecr new features soon
