### ISSUE TITLE
Rename regions attribute to continents.

### ISSUE THREAD

**Issue by ronlinet** [yungifez/skuul#180]
It is more deductive to rename the column `countries.region` to `countries.continent`. 
The `country.subregion` does make generic sense and can be kept as it is.

**Comment by yungifez** [comment]
Again, I use a package called nnjeim/world. I don't handle the hydration of countries and states personally. Thanks for the contribution though

**Comment by ronlinet** [comment]
@yungifez  thank you for having look at this I have moved the issue to the [package author queue](https://github.com/nnjeim/world/issues/40)

**Comment by yungifez** [comment]
Thanks for the contribution. Since this is related to #179, I would be closing that too
