### ISSUE TITLE
Student School Cardinality  Should be many to many

### ISSUE THREAD

**Issue by ronlinet** [yungifez/skuul#181]
One student can study in many schools. 

![Screenshot_2022-11-27_07-40-51](https://user-images.githubusercontent.com/2538315/204136349-feaf17c2-1a11-4de6-88be-51243287e2a1.png)
![Screenshot_2022-11-27_07-48-54](https://user-images.githubusercontent.com/2538315/204136353-a6312a13-3fe9-4c7c-8c3e-6049105d0f08.png)

```
CREATE TABLE IF NOT EXISTS `skuul`.`users_schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT UNSIGNED NOT NULL,
  `schools_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_users_has_schools_schools1_idx` (`schools_id` ASC) VISIBLE,
  INDEX `fk_users_has_schools_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_schools_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `skuul`.`users` (`id`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_users_has_schools_schools1`
    FOREIGN KEY (`schools_id`)
    REFERENCES `skuul`.`schools` (`id`)
    ON DELETE cascade
    ON UPDATE cascade)
```

**Comment by yungifez** [comment]
Can you back this up with real-world experience

I thought of this but the complexity it would bring up in code felt like a deal-breaker to me

Ideally, a student ought to be in just one school, I've never seen a situation where a student is attending 2 high schools at the same time.

**Comment by yungifez** [comment]
I do appreciate your contributions and would like to thank you

**Comment by ronlinet** [comment]
In cross disciplinary education people don’t always study one fixed monolithic program.  You can take different modules from different universities. 

I personally studied in 2012 computing science in one school and Data Mining in a busyness department of another one. 

Another common example would be a lifelong learning span of an adult professional who uses different modules from different schools for personal upskilling. 

We talk here more about vision and long term reusability. A junction table may look scary but it is the bread and butter of relational database. It only increases the system extensibility. 

We are getting back to the inconvenience and limitation of User Entity denormalization.

**Comment by ronlinet** [comment]
It is becoming common to accumulate modules from certified institutes to obtain a diploma. I went through this personally in France and Ireland. I am sure other countries must have similar systems.

**Comment by yungifez** [comment]
Hmmm fair point, I'm dreading implementation and backward compatibility though

I'll do my research on this and check for similar implementations on other school management software. 

But do these schools end up being very related to each other eg different campuses and are you a member of both schools or just benefit from courses from one

**Comment by ronlinet** [comment]
In France I could accumulate different modules from different universities to obtain a degree.  In Ireland It was more about the same university with different campuses from DIFFERENT PHYSICAL ADDRESSES.  

Limiting the student to one physical address will at some point hit the wall.

**Comment by ronlinet** [comment]
> Hmmm fair point, I'm dreading implementation and backward compatibility though
> 
> I'll do my research on this and check for similar implementations on other school management software.
> 
> But do these schools end up being very related to each other eg different campuses and are you a member of both schools or just benefit from courses from one

I saw that you use service classes as repositories. Repository pattern is made specifically for use cases where developers reorganize DB structure. You simply rewrite the CRUD classes and the show goes on.

**Comment by yungifez** [comment]
I could just add a many to many relationship and allow switching of schools by the student

But I'm concerned about stability. I'd love it though if someone with this system sreps up so I would be able to build according to their specs while still maintaining backwards compatibility

**Comment by yungifez** [comment]
Issue would be reopened when planned to be implemented
