### ISSUE TITLE
Country and states are not loaded in dropdown

### ISSUE THREAD

**Issue by dksuresh** [yungifez/skuul#213]
Hi @yungifez,

The Nationality and States are not populating in the dropdown. I ran php artisan db:seed --class=WorldSeeder and re-run the application. In database we ave the records.

<img width="1437" alt="Screenshot 2023-01-14 at 10 41 05 PM" src="https://user-images.githubusercontent.com/1175564/212485881-3164675c-88de-4158-acda-a3ae43e39542.png">

**Comment by yungifez** [comment]
Run 

``` shell
Php artisan optimize:clear
````

**Comment by dksuresh** [comment]
Thanks, data loaded in dropdown.
