### ISSUE TITLE
Super-Admin Failing on Creation

### ISSUE THREAD

**Issue by LokeYourLord** [yungifez/skuul#214]
**Describe the bug**
So, I've finally managed after lots of back and forth to get Skuul running on my system, great. The issue is that now, I want to login wit the super admin credentials of "super@admin.com" and "password", buuuut it doesn't work for some reason. I get the following error:
![image](https://user-images.githubusercontent.com/5807595/215331707-9d9e4f99-3b20-47a3-95d6-a8c02b46020b.png)

Any solution? I checked my MySQL database, and the necessary entries are there. But in the "users" section, there's no users at all.

**Comment by LokeYourLord** [comment]
Issue solved. It took a few tries of seeding the database before it eventually did that.

**Comment by yungifez** [comment]
You could easily just do 

``` shell
php artisan skuul:init 
```

I think I prefer doing this now 

And for updates that aren't major, you could do php artisan skuul:update

Note that this checks you out to the latest branch

It's still in beta though

**Comment by yungifez** [comment]
> Issue solved. It took a few tries of seeding the database before it eventually created the necessary user.

Hmmm, that's weird. 

Normally it should just work

**Comment by LokeYourLord** [comment]
Sounds great, thank you! Additionally, my logo doesn't change after I've added it once. Any idea why? I've tried a "php artisan optimize:clear" run, but it still uses the old logo file.

**Comment by yungifez** [comment]
Can you explain in more detail?

**Comment by LokeYourLord** [comment]
Right so, I added a logo to the"/img/logo/logo.jpg" as described in the ".env" config. That file was loaded, and is displayed on the login page. However, I wanted to change it to another one, but it doesn't update to the new file. Not only that, but even after deleting the old file, it is still visible on the webpage, even after running "php artisan optimize:clear".

**Comment by LokeYourLord** [comment]
Oh and btw, I really think you've got something great here. I want to implement this into our Academy here in Korea, and if you're okay with it, I might in the future (my PHP Laravel skills are crap :3 ) ask you for some features. Of course I'll gladly pay you for the implementation if you're okay with that :)

**Comment by yungifez** [comment]
That is truly confusing 

Try doing a cache:clear on its own

And try using other browsers to see if it's a laravel config cache problem or a browsee cache problem

**Comment by LokeYourLord** [comment]
Okay, did that now. No success, tried other Browsers too but the logo persists.

**Comment by yungifez** [comment]
Try changing your app name and see if this is updated

**Comment by LokeYourLord** [comment]
> Try changing your app name and see if this is updated

I actually did that and also disabled the debug (since it was enabled by default for some reason), and yes that did update while the logo was still stuck.

**Comment by yungifez** [comment]
Using opcache on a local environment does cause some issues with cache haha

Well maybe clearing opcache should completely fix that

**Comment by LokeYourLord** [comment]
> Using opcache on a local environment does cause some issues with cache haha
> 
> Well maybe clearing opcache should completely fix that

I checked if it is using OPCache, it isn't, only Redis so yeah, that wasn't it.

**Comment by LokeYourLord** [comment]
Btw, mind telling me where I can find the navbar (in which file)? I wanna fix a capitalization typo:
![image](https://user-images.githubusercontent.com/5807595/215335725-7e91a215-7d70-4d07-a224-d8622ec7490e.png)
If you see, the "sections" is for some reason in a lowercase "s". Yeah, I'm quite pedantic 😅

**Comment by yungifez** [comment]
Well this is quite strange to me 

Try running php artisan about

**Comment by LokeYourLord** [comment]
Here :)
![image](https://user-images.githubusercontent.com/5807595/215335885-718ce754-41fe-4199-b2f3-51a042cfbfde.png)

Oh btw, there is a bug: If you try to delete a "Class" under "View Classes", it redirects you to a sub-URL with a number. Like ".../classes/5" or ".../classes/2". That brings you to a "500 Error" page. This doesn't happen when deleting class groups or so, so not sure why it does that.

**Comment by yungifez** [comment]
> Btw, mind telling me where I can find the navbar (in which file)? I wanna fix a capitalization typo:
> ![image](https://user-images.githubusercontent.com/5807595/215335725-7e91a215-7d70-4d07-a224-d8622ec7490e.png)
> If you see, the "sections" is for some reason in a lowercase "s". Yeah, I'm quite pedantic 😅

Check the adminlte.php config file

Although changing any file would probably break updates 

You could create a pull request.

I'm currently working on a v2, which addresses speed issues and some critical issues.

You could clone that branch instead and follow the progress

**Comment by LokeYourLord** [comment]
> > Btw, mind telling me where I can find the navbar (in which file)? I wanna fix a capitalization typo:
> > ![image](https://user-images.githubusercontent.com/5807595/215335725-7e91a215-7d70-4d07-a224-d8622ec7490e.png)
> > If you see, the "sections" is for some reason in a lowercase "s". Yeah, I'm quite pedantic 😅
> 
> Check the adminlte.php config file
> 
> Although changing any file would probably break updates
> 
> You could create a pull request.
> 
> I'm currently working on a v2, which addresses speed issues and some critical issues.
> 
> You could clone that branch instead and follow the progress

I'll just wait then and will "composer update" it later :)

**Comment by yungifez** [comment]
> Here :)
> ![image](https://user-images.githubusercontent.com/5807595/215335885-718ce754-41fe-4199-b2f3-51a042cfbfde.png)
> 
> Oh btw, there is a bug: If you try to delete a "Class" under "View Classes", it redirects you to a sub-URL with a number. Like ".../classes/5" or ".../classes/2". That brings you to a "500 Error" page. This doesn't happen when deleting class groups or so, so not sure why it does that.

You could try clearing the views cache

Not sure its going to work but worth a try

**Comment by LokeYourLord** [comment]
> > Here :)
> > ![image](https://user-images.githubusercontent.com/5807595/215335885-718ce754-41fe-4199-b2f3-51a042cfbfde.png)
> > Oh btw, there is a bug: If you try to delete a "Class" under "View Classes", it redirects you to a sub-URL with a number. Like ".../classes/5" or ".../classes/2". That brings you to a "500 Error" page. This doesn't happen when deleting class groups or so, so not sure why it does that.
> 
> You could try clearing the views cache
> 
> Not sure its going to work but worth a try

That one is also getting cleared upon issuing "php artisan optimize:clear" though. Here:
![image](https://user-images.githubusercontent.com/5807595/215336170-dfbc7e2a-a56b-41b0-9bcf-801abf03d133.png)

**Comment by yungifez** [comment]
> Here :)
> ![image](https://user-images.githubusercontent.com/5807595/215335885-718ce754-41fe-4199-b2f3-51a042cfbfde.png)
> 
> Oh btw, there is a bug: If you try to delete a "Class" under "View Classes", it redirects you to a sub-URL with a number. Like ".../classes/5" or ".../classes/2". That brings you to a "500 Error" page. This doesn't happen when deleting class groups or so, so not sure why it does that.

Could you enable app debug and paste the error

**Comment by LokeYourLord** [comment]
Uhh sure, let me create a new class just for demo, 1 sec.

**Comment by LokeYourLord** [comment]
Ok, got it. Here you go. And since it has private info in it, I will delete it soon.
https://flareapp.io/share/DPyDYwQm#F67

**Comment by yungifez** [comment]
You can delete that now

I know what's wrong

And im honestly suprised my test suite didn't catch this

**Comment by yungifez** [comment]
This has been fixed

Pulling the latest changes should solve that

**Comment by LokeYourLord** [comment]
You're making something great here. Seriously, your software is so useful for Academies here in Korea, especially since all other services either suck, are privatized or both. You have no idea... I hope we can work together on more things and features in the future, and I'll make sure to pay you whenever I can :)!

**Comment by LokeYourLord** [comment]
Maybe if you have Discord we can talk live about things if you're interested :)

**Comment by yungifez** [comment]
> Maybe if you have Discord we can talk live about things if you're interested :)

Haha I have discord but I never use it

Haha, you are the first Korean I'm ever interacting with assuming you are Korean

**Comment by yungifez** [comment]
yungifez#3886

This is my username

**Comment by LokeYourLord** [comment]
> > Maybe if you have Discord we can talk live about things if you're interested :)
> 
> Haha I have discord but I never use it
> 
> Haha, you are the first Korean I'm ever interacting with assuming you are Korean

Ah ok, well if you have any other contact methods then send them my way. I use Telegram and stuff too :)

And no I'm not Korean, but I live here and work here. And seriously, Open Source applications like yours are a godsend in a country where Internet Explorer is still in use, 95% of websites look like 90's crap, and they're all so full of information overflow you wouldn't believe. I'm trying to change things up here, trying to make things better really. And the Academy I work for, I'm the web admin. I do plenty of things, but some I always gotta learn more :)

**Comment by yungifez** [comment]
I've been looking for assistance in translation 

Maybe I could use your help. 

I need the help of a community to truly try amd test the software

School management systems are always either crap or too expensive and I'd live to change that

And many can't be used for districts or people with multiple schools but this can do that

**Comment by LokeYourLord** [comment]
> I've been looking for assistance in translation
> 
> Maybe I could use your help.
> 
> I need the help of a community to truly try amd test the software
> 
> School management systems are always either crap or too expensive and I'd live to change that
> 
> And many can't be used for districts or people with multiple schools but this can do that

Yep, and I'd gladly help with both testing and translation. I can translate it into German, Norwegian and Korean for you additionally to checking everything in English (like the minor typos and such).

And you're right, they're all of what you said, and I was hoping for someone to make a system like yours. I'm sure you can achieve lots with this, and I already have plenty of ideas for the future, but of course that will have to wait 😂

**Comment by yungifez** [comment]
Just coming to inform you

V2 has been released

**Comment by LokeYourLord** [comment]
> Just coming to inform you
> 
> V2 has been released

Aww sweet, thanks a lot! Mind giving me a quick rundown on how to update in Laravel? I'm super new to Laravel and the systems, and when I try running the "git" command (to update), it will obviously tell me that the folder already exists. How would I update in such a case?

**Comment by LokeYourLord** [comment]
> > Just coming to inform you
> > V2 has been released
> 
> Aww sweet, thanks a lot! Mind giving me a quick rundown on how to update in Laravel? I'm super new to Laravel and the systems, and when I try running the "git" command (to update), it will obviously tell me that the folder already exists. How would I update in such a case?

I honestly assume it might just be better if I copy the .env file from the previous folder and scrap this one entirely and restart from scratch, since now Node is required as well.

**Comment by LokeYourLord** [comment]
Hmm, so already starting to have issues with this. Here: 
![image](https://user-images.githubusercontent.com/5807595/216755413-7a5e9d0f-42bf-4a5c-a997-7048c4ddd08b.png)

Any idea?

**Comment by yungifez** [comment]
Composer install

Php artisan migrate

Php artisan db:seed --class=RunInProductionSeeder 

npm install

npm run build


This should do

**Comment by yungifez** [comment]
> Hmm, so already starting to have issues with this. Here: 
> ![image](https://user-images.githubusercontent.com/5807595/216755413-7a5e9d0f-42bf-4a5c-a997-7048c4ddd08b.png)
> 
> Any idea? I am running ARM64 Ubuntu, in case that matters.

Your node seems outdated

Try updating it

**Comment by LokeYourLord** [comment]
> > Hmm, so already starting to have issues with this. Here:
> > ![image](https://user-images.githubusercontent.com/5807595/216755413-7a5e9d0f-42bf-4a5c-a997-7048c4ddd08b.png)
> > Any idea? I am running ARM64 Ubuntu, in case that matters.
> 
> Your node seems outdated
> 
> Try updating it

Thanks, I'll try that. Updating NodeJS seems to be tricky for some reason because easy commands for doing so aren't floating around much, but I think I've done it now. I'll try again.

**Comment by yungifez** [comment]
You could use nvm 

Nvm makes it easy to keep track of node

**Comment by LokeYourLord** [comment]
> You could use nvm
> 
> Nvm makes it easy to keep track of node

Thanks, but I used this method:
npm cache clean -f
npm install -g n
n stable
