### ISSUE TITLE
Add internal database next to Amazon's external database memory

### ISSUE THREAD

**Issue by seti1212** [yungifez/skuul#230]
Hello
 If you can add an option to the configuration section, by activating it, the database type will be internal
 And if we give it an off value, the data storage location will be changed to database amazon

 In general, my applying for is to use our own hosting spaces to store the files and not have the trouble of accessing the apis of the storage location.

 Thankful

**Comment by yungifez** [comment]
Hello, please can you clarify that you mean amazon s3 for file storage?

**Comment by yungifez** [comment]
Hello, please can you clarify that you mean amazon s3 for file storage?

**Comment by seti1212** [comment]
> Hello, please can you clarify that you mean amazon s3 for file storage?

Hello
 Now we need to fill the following api in the file `.env` so that our project will create the database in Amazon
 ```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=
AWS_USE_PATH_STYLE_ENDPOINT=
```

In this case, the database will be created on Amazon, but we want the project database to be created on our computer so that we can access it more easily.

 For this reason,That's why I want an option to the `.env' file that if we give it the true value, the database will be created on our computer, and if we give it the false value Amazon will still be used as a database as before.

**Comment by yungifez** [comment]
I'm sorry, I still do not understand what you mean

Do you mean file system or database?

**Comment by yungifez** [comment]
> > Hello, please can you clarify that you mean amazon s3 for file storage?
> 
> Hello
>  Now we need to fill the following api in the file `.env` so that our project will create the database in Amazon
>  ```
> AWS_ACCESS_KEY_ID=
> AWS_SECRET_ACCESS_KEY=
> AWS_DEFAULT_REGION=
> AWS_USE_PATH_STYLE_ENDPOINT=
> ```
> 
> In this case, the database will be created on Amazon, but we want the project database to be created on our computer so that we can access it more easily.
> 
>  For this reason,That's why I want an option to the `.env` file that if we give it the true value, the database will be created on our computer, and if we give it the false value Amazon will still be used as a database as before.

So you want a local database for testing?

Or why do you want this

**Comment by seti1212** [comment]
Can't say I want the project database space next to it for testing
 Because it has easier access and higher security, and it is also possible that the space provided by Amazon for information storage is limited

**Comment by seti1212** [comment]
> 

I mean changing the location of the database

**Comment by yungifez** [comment]
So let me get this right, you want to connect to an amazon database?

Or you want to connect to a local database?

**Comment by yungifez** [comment]
> > I'm sorry, I still do not understand what you mean
> Do you mean file system or database?
> 
> I mean changing the location of the database

You would love your database to be hosted locally?

**Comment by seti1212** [comment]
> Would you like your database to be hosted locally?

yes

So that by changing the value of a variable, the location of the database changes to Amazon or to our computer
 
for example : 
  ```  
#True for amazon and false for local  Database_type=False
  ```

**Comment by yungifez** [comment]
You could just create .env.amazon and .env.local and fill in each detail. I don't take care of the database drivers and this looks like a problem unique to you


When you want to use your amazon database, you can just do something like this

```
Cp .env.amazon .env
```

And for local

```
Cp .env.local .env
```

This should work

**Comment by seti1212** [comment]
> You could just create .env.amazon and .env.local and fill in each detail. I don't take care of the database drivers and this looks like a problem unique to you
> 
> When you want to use your amazon database, you can just do something like this
> 
> ```
> Cp .env.amazon .env
> ```
> 
> And for local
> 
> ```
> Cp .env.local .env
> ```
> 
> This should work

Does this mean that the location of the database is changed from Amazon to local?
 And no need to import amazon apis to connect to its database?

**Comment by seti1212** [comment]
And can the following code be used for other sources whose database is from Amazon so that their database is also changed from Amazon to local ?
```
Cp .env.local .env
```

**Comment by yungifez** [comment]
> > You could just create .env.amazon and .env.local and fill in each detail. I don't take care of the database drivers and this looks like a problem unique to you
> > 
> > When you want to use your amazon database, you can just do something like this
> > 
> > ```
> > Cp .env.amazon .env
> > ```
> > 
> > And for local
> > 
> > ```
> > Cp .env.local .env
> > ```
> > 
> > This should work
> 
> Does this mean that the location of the database is changed from Amazon to local?
>  And no need to import ` amazon apis` to connect to its database?
> 

Connecting to amazons database should be identical to connecting to a regular database 

See this for reference 

https://laracasts.com/discuss/channels/laravel/how-do-i-connect-my-app-to-my-aws-rds-instance-from-my-aws-ec2-instance

You'd have to fill out the 2 env files to your wish, what I gave is only a suggestion 

And note that subsequent updates may get rid of those files

**Comment by yungifez** [comment]
> And can the following code be used for other sources whose database is from Amazon so that their database is also changed from Amazon to local ?
> ```
> Cp .env.local .env
> ```

This just copies the values from one file to another

**Comment by seti1212** [comment]
So why can't you help me to create a local database?

**Comment by seti1212** [comment]
Because I want to not use Amazon as a database

**Comment by yungifez** [comment]
You don't want to use amazon as the database?

Those AWS credentials aren't for database connections

**Comment by seti1212** [comment]
Really ?
 So what does this project use as a database?
 And is it mandatory to enter AWS credentials to run the project?

**Comment by yungifez** [comment]
Those AWS credentials are optional for amazon aws 

Any mysql database can be used in this project 

It is just a laravel app

https://laravel.com/docs/9.x/database#configuration

This should help

**Comment by seti1212** [comment]
thanks for your help

 Does this mean that the project does not need an api to connect to the database, and even if we do not fill in the following items, the project will still run?

 The reason for asking my question was;  Because I thought that Amazon could be used as a database

**Comment by yungifez** [comment]
I tried deploying on vercel. Didn't work

To connect to a database you need the following

The host, the port, the username, and finally the password


To simplify the installation process, run the following 

```
Php artisan skuul:init
```

**Comment by seti1212** [comment]
Thanks, I just have one more question and then I won't disturb your time anymore.

 Can this project be implemented on sites like replit, heroku, and glitch?

 Because I tried to run it on replit before, but every time I encountered various errors in the project link.

**Comment by yungifez** [comment]
I have not usrd any of these services

But a linux based host with access to command line would work

**Comment by yungifez** [comment]
There is no problem, you arent wasting my time

**Comment by seti1212** [comment]
thanks for your help
 Hope to meet
🌹

**Comment by yungifez** [comment]
You can in fact host this on jeroku by what I'm reading

**Comment by seti1212** [comment]
So I go to heroku again

**Comment by yungifez** [comment]
Hello
