### ISSUE TITLE
Multiple Suggestions

### ISSUE THREAD

**Issue by LokeYourC3PH** [yungifez/skuul#311]
**Is your feature request related to a problem? Please describe.**
Suggestion 1:
A note section.

Suggestion 2:
A finances section.

Suggestion 3:
A books section.

Suggestion 4:
Default nation/country (or other default values) when creating a profile, and the ability to skip certain required fields.

Suggestion 5:
A "blog/feed" sort-of function for each class/student.

**Describe the solution you'd like**
Suggestion 1:
It would be great having the ability to add notes to teachers/students, both visible to them and private ones only visible to administration. For example, a note about x student that they come 15 minutes late every day, or whatever. Just the ability to create custom notes for and on any individual. Students can create notes for themselves, teachers for themselves and their students, and administration for everyone. Teachers can set the notes to be visible for either both student and teachers/administration, or only teachers/administration. And administration can set notes to only be visible/editable by administration, and teachers/administration. This section would help immensely with building the next two suggestions.

Suggestion 2:
A finance section, which functions similar to the notes section, but is displayed on the student's/parent's/teacher's profile with a total sum of what is owed, calculated by what has been added in the finance section. Let's say, a student buys a book or other materials. These are added in the finance section under new entries for each material, and a sum of said material (currency can be chosen/set, with a default currency that can be set in the settings of administration). This would make it so that parents or students have a way of seeing their total, and also where to pay it to (for example adding below said owed value a section with bank information, QR code, or other payment methods that can be added by administration with a custom note below their total sum).

Suggestion 3:
A way to add books, their cover images and names and price, and to then add these to students with a toggle for paid or unpaid. These can then be added to students individually to see which books they currently are using (maybe even a sub-section for each book with chapters to mark progress, but it isn't a requirement), that would be useful for seeing their curriculum progress and also to see if they have paid for a book yet or not. And once a book has been finished, a way to mark it as "Complete", which makes it grey out in the list/grid, and active ones are of course not greyed out.

Suggestion 4:
This one would help with selection really, because starting from "Afghanistan" or such is kind of annoying, as all we really need is a default set. It's fine having the ability to choose country, province, city, but there should be a default set system-wide (same goes for other values as well). Also, the ability to not fill in irrelevant stuff such as blood-type, religious belief, etc. would also be massively appreciated. Last but not least, the ability to not enter Email/Password when making a student profile would be beneficial so that it can be used for administrative purposes, because not every student will use the system or needs to use it, it is only being used to keep track of their information and curriculum. However, with Suggestion 5, it might be used for more than so.

Suggestion 5:
A "blog/feed" sort-of function for each class and/or student. Basically, when students or parents login to their accounts, on their dashboard, they see a "feed", kind of like Facebook feed, where they see posts by x teacher, with x content (today's homework, a link to materials, etc.). They see their class content maybe on one side (left side with their class feed), and personal notes on the opposite (personal notes left by teachers, maybe on the right side of their dashboard). This would make it so students have a reason to come to use the system as well, expanding the userbase, seeing their details, feed with class content and personal notes, their fees, book progress, etc.

**Comment by LokeYourLord** [comment]
Suggestion 6:
Roundcube Email account creation. The ability to create an Email account while creating a user profile would be immensely helpful with creating student profiles. A toggle that is below the "Email address" box to establish a user with the given Email & Password would be great.

Reference:
![image](https://user-images.githubusercontent.com/5807595/234490646-6289f5aa-9598-4b77-909c-bb2bfd7922dc.png)
In the red marked area, a toggle that is by default off, but when toggled on, creates a user account for said Email & Password in the Roundcube mail server. That way, accounts can be created by Administrators and maybe Teachers for their students without needing them to register their own Email address.
