### ISSUE TITLE
Student attendance

### ISSUE THREAD

**Issue by mdzahid-pro** [yungifez/skuul#323]
I didn't see student attendance that is very important for a school

**Comment by yungifez** [comment]
It would come soon in the future. I've not had time to implement things like that

**Comment by yungifez** [comment]
Since no more responses, I'll be closing it fir now

**Comment by hikoukinin** [comment]
Any update, I am also very interested in student attendance.

**Comment by yungifez** [comment]
Unfortunately I'm not able to work on this feature for the foreseeable future 



I'm very busy with other things
