### ISSUE TITLE
Login Details for https://yungifez.xyz/register

### ISSUE THREAD

**Issue by mahesh-riddles** [yungifez/skuul#339]
Can I get the login details for the demo?

**Comment by yungifez** [comment]
super@admin.com

helloworld

**Comment by yungifez** [comment]
if helloworld does not work try password

**Comment by yungifez** [comment]
Can I close this?

**Comment by mahesh-riddles** [comment]
Yes, It is working. Huge work you have done. Thanks a lot!

**Comment by mahesh-riddles** [comment]
Sure..
