### ISSUE TITLE
Migration Issue

### ISSUE THREAD

**Issue by itsmemanoj** [yungifez/skuul#355]
**SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'timetable_time_slot_weekday_timetable_time_slot_weekdayable_id_foreign' is too long (Connection: mysql, SQL: alter table `timetable_time_slot_weekday` add constraint `timetable_time_slot_weekday_timetable_time_slot_weekdayable_id_foreign` foreign key (`timetable_time_slot_weekdayable_id`) references `timetable_time_slot_weekdayables` (`id`) on delete cascade on update cascade)**

Actually above is second error, First error was column renaming, **timetable_time_slot_weekday** on this table, column renaming from subject_id to timetable_time_slot_weekdayable_id. Error said: key is required for foreign key and can not be renamed.
I solved that by alterting table migration, 
After that above was second error.

**To Reproduce**
1. AFter completeing setup process, just start migration and you get error

Device:
Windows 10
Laragon
PHP 8.2
Apache

**Comment by yungifez** [comment]
What version of mysql are you on?

**Comment by yungifez** [comment]
What version of mysql are you on?

**Comment by yungifez** [comment]
Hello is this still happening or can I close this issue?
