### ISSUE TITLE
Approval of users 

### ISSUE THREAD

**Issue by cute-poison** [yungifez/skuul#359]
The approval of users isn't giving options to accept or reject users or applicants

**Comment by yungifez** [comment]
Haha like I said

I can't fix the bug

No pc🤣🤣

**Comment by cute-poison** [comment]
It's sad 😭 is there anyway you can guide me towards fixing it please it
will really be of help that is what is keeping me from completion

**Comment by yungifez** [comment]
Haha I don't know what the problem is for now

**Comment by yungifez** [comment]
Try changing the line

`        $this->statuses = $this->applicant->accountApplication->statuses()->get();`

To this

`        $this->statuses = $this->applicant->accountApplication->getAllStatuses();`



I'm not sure

**Comment by cute-poison** [comment]
Couldn't find the file
Where is inserted could you help me out  $this->statuses =
$this->applicant->accountApplication->statuses()->get();

**Comment by cute-poison** [comment]
Please any update on your system

**Comment by yungifez** [comment]
My PC is still damaged sorry

**Comment by yungifez** [comment]
Fixed in #261
