### ISSUE TITLE
Unable to login as admin

### ISSUE THREAD

**Issue by qaribhinder** [yungifez/skuul#360]
I have tried both
Password & helloworld
With super@admin.com & admin

**Comment by yungifez** [comment]
Try password

**Comment by qaribhinder** [comment]
Both tried
1. password
2. helloworld

**Comment by yungifez** [comment]
It is 

super@admin.com
Password

Works on my end

**Comment by qaribhinder** [comment]
Tried both usernames.
1. super@admin.com
2. admin

**Comment by qaribhinder** [comment]
https://yungifez.xyz/login

super@admin.com
Password


It's not working on my side

**Comment by yungifez** [comment]
That's weird and unheard of

**Comment by yungifez** [comment]
Make sure you don't have caps on
